plugins:
  stale_topics_enabled:
    default: true
    client: true
  stale_topics_remind_staff:
    default: true
  stale_topics_remind_staff_duration: 0
  stale_topics_remind_staff_interval_units:
    type: enum
    default: 'days'
    choices:
      - minutes
      - hours
      - days
      - months
  stale_topics_retry_remind_staff_duration: 0
  stale_topics_retry_remind_staff_interval_units:
    type: enum
    default: 'days'
    choices:
      - minutes
      - hours
      - days
      - months
  stale_topics_remind_staff_group: "staff"
  stale_topics_max_client_replies:
    default: 2
  stale_topics_retry_remind_client_duration: 0
  stale_topics_retry_remind_client_interval_units:
    client: true
    type: enum
    default: 'days'
    choices:
      - minutes
      - hours
      - days
      - months
  stale_topics_client_staff_whisper_reminder_enabled:
    default: true
  stale_topics_show_sidekiq:
    default: true
    client: true
  stale_topics_silence_on_whisper:
    default: true
  stale_topics_ignored_categories:
    client: true
    type: list
    default: staff
